export const TEXT = {
  nav: {
    home: "Home",
    pipes: "Pipes",
    tobacco: "Tobacco",
    cellar: "Cellar",
    community: "Community",
    profile: "Profile",
    help: "Help",
    faq: "FAQ",
    support: "Support",
    terms: "Terms",
    privacy: "Privacy",
    quickAccess: "Quick Access",
    syncing: "Syncing...",
  },
  auth: {
    loginPrompt: "Please sign in to continue",
    login: "Sign In",
  },
  common: {
    loading: "Loading...",
    save: "Save",
    cancel: "Cancel",
    delete: "Delete",
    edit: "Edit",
    close: "Close",
    yes: "Yes",
    no: "No",
    ok: "OK",
    search: "Search",
    filter: "Filter",
    sort: "Sort",
    add: "Add",
    remove: "Remove",
    clear: "Clear",
    apply: "Apply",
    reset: "Reset",
  },
  subscription: {
    trialEndedTitle: "Your trial has ended",
    trialEndedBody: "Upgrade to Premium to continue enjoying unlimited access to all features.",
    continueFree: "Continue Free",
    subscribe: "Subscribe",
  },
  admin: {
    subscriptionSupport: "Subscription Support",
    userReport: "User Report",
    contentModeration: "Content Moderation",
    eventsLog: "Events Log",
  },
};