export const TEXT = {
  nav: {
    home: "ホーム",
    pipes: "パイプ",
    tobacco: "タバコ",
    cellar: "セラー",
    community: "コミュニティ",
    profile: "プロフィール",
    help: "ヘルプ",
    faq: "よくある質問",
    support: "サポート",
    terms: "利用規約",
    privacy: "プライバシー",
    quickAccess: "クイックアクセス",
    syncing: "同期中...",
  },
  auth: {
    loginPrompt: "続けるにはサインインしてください",
    login: "サインイン",
  },
  common: {
    loading: "読み込み中...",
    save: "保存",
    cancel: "キャンセル",
    delete: "削除",
    edit: "編集",
    close: "閉じる",
    yes: "はい",
    no: "いいえ",
    ok: "OK",
    search: "検索",
    filter: "フィルター",
    sort: "並び替え",
    add: "追加",
    remove: "削除",
    clear: "クリア",
    apply: "適用",
    reset: "リセット",
  },
  subscription: {
    trialEndedTitle: "トライアル期間が終了しました",
    trialEndedBody: "プレミアムにアップグレードして、すべての機能への無制限アクセスをお楽しみください。",
    continueFree: "無料で続ける",
    subscribe: "サブスクライブ",
  },
  admin: {
    subscriptionSupport: "サブスクリプションサポート",
    userReport: "ユーザーレポート",
    contentModeration: "コンテンツモデレーション",
    eventsLog: "イベントログ",
  },
};