export const TEXT = {
  nav: {
    home: "Home",
    pipes: "Pijpen",
    tobacco: "Tabak",
    cellar: "Kelder",
    community: "Gemeenschap",
    profile: "Profiel",
    help: "Hulp",
    faq: "Veelgestelde vragen",
    support: "Ondersteuning",
    terms: "Voorwaarden",
    privacy: "Privacy",
    quickAccess: "Snelle toegang",
    syncing: "Synchroniseren...",
  },
  auth: {
    loginPrompt: "Log in om door te gaan",
    login: "Inloggen",
  },
  common: {
    loading: "Laden...",
    save: "Opslaan",
    cancel: "Annuleren",
    delete: "Verwijderen",
    edit: "Bewerken",
    close: "Sluiten",
    yes: "Ja",
    no: "Nee",
    ok: "OK",
    search: "Zoeken",
    filter: "Filteren",
    sort: "Sorteren",
    add: "Toevoegen",
    remove: "Verwijderen",
    clear: "Wissen",
    apply: "Toepassen",
    reset: "Resetten",
  },
  subscription: {
    trialEndedTitle: "Uw proefperiode is afgelopen",
    trialEndedBody: "Upgrade naar Premium om te blijven genieten van onbeperkte toegang tot alle functies.",
    continueFree: "Ga gratis verder",
    subscribe: "Abonneren",
  },
  admin: {
    subscriptionSupport: "Abonnementsondersteuning",
    userReport: "Gebruikersrapport",
    contentModeration: "Inhoudsbeheer",
    eventsLog: "Gebeurtenissenlogboek",
  },
};