export const TEXT = {
  nav: {
    home: "Hem",
    pipes: "Pipor",
    tobacco: "Tobak",
    cellar: "Källare",
    community: "Gemenskap",
    profile: "Profil",
    help: "Hjälp",
    faq: "Vanliga frågor",
    support: "Support",
    terms: "Villkor",
    privacy: "Integritet",
    quickAccess: "Snabbåtkomst",
    syncing: "Synkroniserar...",
  },
  auth: {
    loginPrompt: "Logga in för att fortsätta",
    login: "Logga in",
  },
  common: {
    loading: "Laddar...",
    save: "Spara",
    cancel: "Avbryt",
    delete: "Ta bort",
    edit: "Redigera",
    close: "Stäng",
    yes: "Ja",
    no: "Nej",
    ok: "OK",
    search: "Sök",
    filter: "Filtrera",
    sort: "Sortera",
    add: "Lägg till",
    remove: "Ta bort",
    clear: "Rensa",
    apply: "Tillämpa",
    reset: "Återställ",
  },
  subscription: {
    trialEndedTitle: "Din provperiod har avslutats",
    trialEndedBody: "Uppgradera till Premium för att fortsätta njuta av obegränsad åtkomst till alla funktioner.",
    continueFree: "Fortsätt gratis",
    subscribe: "Prenumerera",
  },
  admin: {
    subscriptionSupport: "Prenumerationssupport",
    userReport: "Användarrapport",
    contentModeration: "Innehållsmoderering",
    eventsLog: "Händelselogg",
  },
};