/**
 * valueRefreshService
 *
 * Reusable service for auto-seeding and refreshing item valuations.
 * Module-agnostic — works for whiskeykeeper bottles, pipekeeper pipes and
 * tobacco blends, and any future module that uses ItemValueSnapshot /
 * BottleValueSnapshot.
 *
 * Public API:
 *   seedInitialSnapshotIfMissing(item, moduleKey, itemType, userEmail, base44, existingSnapshots)
 *   refreshItemValue(item, moduleKey, itemType, userEmail, base44, collectionContext)
 *   runScheduledRefreshForUser(userEmail, moduleKey, base44)
 *
 * Dependencies (passed in, never imported directly to keep this portable):
 *   base44  – the Base44 client instance
 *   valueEngine helpers – imported from the canonical valueEngine
 */

import {
  buildValuationSnapshot,
  resolveValueTrend,
} from '@/components/valuation/valueEngine';
import { buildCigarMarketValuationPatch, deriveCigarMarketValuation } from '@/utils/cigarMarketValuation';

// ─────────────────────────────────────────────────────────────────────────────
// Internal helpers
// ─────────────────────────────────────────────────────────────────────────────

function todayISODate() {
  return new Date().toISOString().slice(0, 10);
}

/**
 * Returns true if a snapshot already exists for this item on today's date.
 * Prevents duplicate auto-generated snapshots within the same day.
 */
function snapshotExistsToday(existingSnapshots, today) {
  return existingSnapshots.some((s) => s.snapshot_date === today);
}

function hasPatchDiff(item, patch) {
  return Object.entries(patch).some(([key, next]) => {
    const prev = item?.[key];
    if (typeof next === 'number') return Math.abs((Number(prev) || 0) - next) > 0.005;
    return (prev ?? null) !== (next ?? null);
  });
}

function groupByItemId(rows = []) {
  return rows.reduce((acc, row) => {
    const itemId = row?.item_id;
    if (!itemId) return acc;
    if (!acc[itemId]) acc[itemId] = [];
    acc[itemId].push(row);
    return acc;
  }, {});
}

/**
 * Build the payload object for a new BottleValueSnapshot (whiskeykeeper).
 */
function buildBottleSnapshotPayload(bottle, snap, userEmail, today, isAutoGenerated, notes) {
  return {
    bottle_id: bottle.id,
    created_by: userEmail,
    snapshot_date: today,
    retail_price: bottle.retail_price || null,
    aftermarket_price: bottle.aftermarket_price || null,
    collector_value: bottle.collector_value || null,
    computed_current_value: snap.currentValue || null,
    value_confidence: snap.confidence || 'low',
    source: snap.source || null,
    rarity_score: snap.rarityScore || null,
    replacement_difficulty: snap.replacementDifficulty || null,
    is_auto_generated: isAutoGenerated,
    notes: notes || null,
  };
}

/**
 * Build the payload object for a new ItemValueSnapshot (any module).
 */
function buildItemSnapshotPayload(item, moduleKey, itemType, snap, valueTrend, userEmail, today, isAutoGenerated, notes) {
  return {
    module_key: moduleKey,
    item_type: itemType,
    item_id: item.id,
    created_by: userEmail,
    snapshot_date: today,
    retail_value: item.retail_price || item.retail_value || null,
    market_value: item.aftermarket_price || item.market_value || item.market_estimated_total_value || null,
    collector_value: item.collector_value || null,
    computed_current_value: snap.currentValue || null,
    computed_value: snap.currentValue || null,
    value_confidence: snap.confidence || 'low',
    confidence: snap.confidence || 'low',
    source: snap.source || null,
    rarity_score: snap.rarityScore || null,
    replacement_difficulty: snap.replacementDifficulty || null,
    trend_basis: valueTrend || snap.trend || 'unknown',
    recommendation: snap.holdRecommendation || null,
    is_auto_generated: isAutoGenerated,
    notes: notes || null,
  };
}

// ─────────────────────────────────────────────────────────────────────────────
// Default ValuationSettings values used when no settings document exists
// ─────────────────────────────────────────────────────────────────────────────

export const DEFAULT_VALUATION_SETTINGS = {
  auto_value_refresh_enabled: true,
  value_refresh_cadence: 'weekly',
  auto_generate_snapshots: true,
  refresh_on_item_create: true,
  refresh_on_first_view_if_missing: true,
  last_auto_refresh_at: null,
};

// ─────────────────────────────────────────────────────────────────────────────
// Load ValuationSettings for a user (falls back to defaults)
// ─────────────────────────────────────────────────────────────────────────────

export async function loadValuationSettings(userEmail, base44) {
  try {
    const rows = await base44.entities.ValuationSettings.filter({ created_by: userEmail }, null, 1);
    if (rows && rows.length > 0) {
      return { ...DEFAULT_VALUATION_SETTINGS, ...rows[0] };
    }
  } catch {
    // entity may not exist yet — fall through to defaults
  }
  return { ...DEFAULT_VALUATION_SETTINGS };
}

// ─────────────────────────────────────────────────────────────────────────────
// Auto-seed: create a first snapshot when none exist for an item
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Seeds the first ItemValueSnapshot / BottleValueSnapshot for an item if none
 * exist yet.  Safe to call unconditionally — it checks before writing.
 *
 * @param {object} item         – The item record (Bottle, Pipe, TobaccoBlend, …)
 * @param {string} moduleKey    – e.g. 'whiskeykeeper' | 'pipekeeper'
 * @param {string} itemType     – e.g. 'bottle' | 'pipe' | 'tobacco'
 * @param {string} userEmail
 * @param {object} base44       – Base44 client
 * @param {Array}  existingSnapshots – Already loaded snapshots (may be empty)
 * @param {object} [collectionContext] – { bottles, valueHistory } for valueEngine
 * @returns {boolean} true if a snapshot was created, false otherwise
 */
export async function seedInitialSnapshotIfMissing(
  item,
  moduleKey,
  itemType,
  userEmail,
  base44,
  existingSnapshots = [],
  collectionContext = {}
) {
  if (!item || !userEmail) return false;
  if (existingSnapshots.length > 0) return false;

  const today = todayISODate();
  const snap = buildValuationSnapshot(item, moduleKey, {
    bottles: collectionContext.bottles || [],
    valueHistory: [],
  });

  if (!snap || !snap.currentValue) return false;

  try {
    // For whiskeykeeper, write to BottleValueSnapshot for backward compat
    if (moduleKey === 'whiskeykeeper') {
      await base44.entities.BottleValueSnapshot.create(
        buildBottleSnapshotPayload(item, snap, userEmail, today, true, 'Auto-generated on first view')
      );
    }
    // Always write to ItemValueSnapshot for cross-module consistency
    await base44.entities.ItemValueSnapshot.create(
      buildItemSnapshotPayload(item, moduleKey, itemType, snap, 'unknown', userEmail, today, true, 'Auto-generated on first view')
    );
    return true;
  } catch (e) {
    console.error('[valueRefreshService] seedInitialSnapshotIfMissing failed', e);
    return false;
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// Manual refresh: "Refresh Value Now"
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Immediately re-computes and saves a new snapshot for one item.
 * Does NOT deduplicate by date — the user explicitly requested a refresh.
 *
 * @param {object} item
 * @param {string} moduleKey
 * @param {string} itemType
 * @param {string} userEmail
 * @param {object} base44
 * @param {object} [collectionContext]
 * @returns {object|null} The new snapshot payload (for optimistic UI update), or null on failure
 */
export async function refreshItemValue(
  item,
  moduleKey,
  itemType,
  userEmail,
  base44,
  collectionContext = {}
) {
  if (!item || !userEmail) return null;

  const today = todayISODate();
  const snap = buildValuationSnapshot(item, moduleKey, {
    bottles: collectionContext.bottles || [],
    valueHistory: collectionContext.valueHistory || [],
  });
  const valueTrend = resolveValueTrend(collectionContext.valueHistory || []);

  if (!snap) return null;

  try {
    if (moduleKey === 'whiskeykeeper') {
      await base44.entities.BottleValueSnapshot.create(
        buildBottleSnapshotPayload(item, snap, userEmail, today, true, 'Refreshed via Refresh Value Now')
      );
    }
    await base44.entities.ItemValueSnapshot.create(
      buildItemSnapshotPayload(item, moduleKey, itemType, snap, valueTrend, userEmail, today, true, 'Refreshed via Refresh Value Now')
    );

    // Return a synthetic snapshot record so the caller can update state
    // immediately without waiting for a DB round-trip
    return {
      bottle_id: moduleKey === 'whiskeykeeper' ? item.id : undefined,
      item_id: item.id,
      snapshot_date: today,
      computed_current_value: snap.currentValue,
      value_confidence: snap.confidence,
      source: snap.source,
      rarity_score: snap.rarityScore,
      replacement_difficulty: snap.replacementDifficulty,
      is_auto_generated: true,
    };
  } catch (e) {
    console.error('[valueRefreshService] refreshItemValue failed', e);
    return null;
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// Scheduled refresh: called by the cloud function or a manual "run now"
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Determines whether a scheduled refresh is due for a user based on their
 * ValuationSettings.
 *
 * @param {object} settings  ValuationSettings record (or defaults)
 * @returns {boolean}
 */
export function isRefreshDue(settings) {
  if (!settings.auto_value_refresh_enabled) return false;
  if (!settings.last_auto_refresh_at) return true;

  const last = new Date(settings.last_auto_refresh_at);
  const now = new Date();
  const diffDays = (now - last) / (1000 * 60 * 60 * 24);

  if (settings.value_refresh_cadence === 'weekly') return diffDays >= 7;
  if (settings.value_refresh_cadence === 'monthly') return diffDays >= 30;
  return false;
}

/**
 * Runs a scheduled value refresh for all items belonging to one user/module.
 *
 * Algorithm:
 *  1. Load ValuationSettings — if refresh not due, skip.
 *  2. Fetch all items for the user in the given module.
 *  3. For each item, load today's snapshots and skip if one already exists.
 *  4. Compute value via buildValuationSnapshot and write new snapshot.
 *  5. Update last_auto_refresh_at in ValuationSettings.
 *
 * @param {string} userEmail
 * @param {string} moduleKey   'whiskeykeeper' | 'pipekeeper' | …
 * @param {object} base44      Base44 client
 * @returns {{ refreshed: number, skipped: number, errors: number }}
 */
export async function runScheduledRefreshForUser(userEmail, moduleKey, base44) {
  const result = { refreshed: 0, skipped: 0, errors: 0 };

  const settings = await loadValuationSettings(userEmail, base44);

  if (!isRefreshDue(settings)) {
    return result;
  }

  if (!settings.auto_generate_snapshots) {
    return result;
  }

  const today = todayISODate();

  try {
    let items = [];
    if (moduleKey === 'whiskeykeeper') {
      items = await base44.entities.Bottle.filter({ created_by: userEmail }, '-created_date', 1000).catch(() => []);
    } else if (moduleKey === 'pipekeeper') {
      const [pipes, tobaccos] = await Promise.all([
        base44.entities.Pipe.filter({ created_by: userEmail }, '-created_date', 1000).catch(() => []),
        base44.entities.TobaccoBlend.filter({ created_by: userEmail }, '-created_date', 1000).catch(() => []),
      ]);
      items = [
        ...pipes.map((p) => ({ ...p, _itemType: 'pipe' })),
        ...tobaccos.map((t) => ({ ...t, _itemType: 'tobacco' })),
      ];
    } else if (moduleKey === 'winekeeper') {
      items = await base44.entities.Wine.filter({ created_by: userEmail }, '-created_date', 1000).catch(() => []);
      items = items.map((w) => ({ ...w, _itemType: 'wine' }));
    } else if (moduleKey === 'cigarkeeper') {
      const [cigars, priceObservations, valueSnapshots] = await Promise.all([
        base44.entities.Cigar.filter({ created_by: userEmail }, '-created_date', 1000).catch(() => []),
        base44.entities.PriceObservation.filter(
          { created_by: userEmail, module_key: 'cigarkeeper', item_type: 'cigar' },
          '-observed_date',
          5000
        ).catch(() => []),
        base44.entities.ItemValueSnapshot.filter(
          { created_by: userEmail, module_key: 'cigarkeeper', item_type: 'cigar' },
          '-snapshot_date',
          5000
        ).catch(() => []),
      ]);
      items = Array.isArray(cigars) ? cigars.map((c) => ({ ...c, _itemType: 'cigar' })) : [];
      const observationsByItem = groupByItemId(priceObservations);
      const snapshotsByItem = groupByItemId(valueSnapshots);
      items = items.map((item) => {
        const derivation = deriveCigarMarketValuation(item, {
          observations: observationsByItem[item.id] || [],
          snapshots: snapshotsByItem[item.id] || [],
        });
        const patch = buildCigarMarketValuationPatch(item, derivation);
        return patch ? { ...item, _marketPatch: patch } : item;
      });
    }

    for (const item of items) {
      try {
        const itemType = item._itemType || (moduleKey === 'whiskeykeeper' ? 'bottle' : moduleKey === 'winekeeper' ? 'wine' : 'other');

        if (moduleKey === 'cigarkeeper' && item._marketPatch && hasPatchDiff(item, item._marketPatch)) {
          try {
            await base44.entities.Cigar.update(item.id, item._marketPatch);
          } catch {
            // Non-fatal; snapshot refresh can still proceed from current in-memory values
          }
        }

        // Check for a snapshot already created today
        let existingToday = [];
        if (moduleKey === 'whiskeykeeper') {
          existingToday = await base44.entities.BottleValueSnapshot.filter({
            bottle_id: item.id,
            created_by: userEmail,
            snapshot_date: today,
          }, null, 1).catch(() => []);
        } else {
          existingToday = await base44.entities.ItemValueSnapshot.filter({
            item_id: item.id,
            created_by: userEmail,
            snapshot_date: today,
          }, null, 1).catch(() => []);
        }

        if (snapshotExistsToday(existingToday, today)) {
          result.skipped++;
          continue;
        }

        const snapshotInput = moduleKey === 'cigarkeeper' && item._marketPatch
          ? { ...item, ...item._marketPatch }
          : item;
        const snap = buildValuationSnapshot(snapshotInput, moduleKey, { bottles: items, valueHistory: [] });
        if (!snap || !snap.currentValue) {
          result.skipped++;
          continue;
        }

        if (moduleKey === 'whiskeykeeper') {
          await base44.entities.BottleValueSnapshot.create(
            buildBottleSnapshotPayload(item, snap, userEmail, today, true, 'Auto-generated by scheduled refresh')
          );
        }
        await base44.entities.ItemValueSnapshot.create(
          buildItemSnapshotPayload(snapshotInput, moduleKey, itemType, snap, 'unknown', userEmail, today, true, 'Auto-generated by scheduled refresh')
        );
        result.refreshed++;
      } catch {
        result.errors++;
      }
    }

    // Update last_auto_refresh_at
    try {
      const existing = await base44.entities.ValuationSettings.filter({ created_by: userEmail }, null, 1).catch(() => []);
      const nowISO = new Date().toISOString();
      if (existing && existing.length > 0) {
        await base44.entities.ValuationSettings.update(existing[0].id, { last_auto_refresh_at: nowISO });
      } else {
        await base44.entities.ValuationSettings.create({
          ...DEFAULT_VALUATION_SETTINGS,
          created_by: userEmail,
          last_auto_refresh_at: nowISO,
        });
      }
    } catch {
      // Non-fatal — settings update failure should not block the refresh result
    }
  } catch (e) {
    console.error('[valueRefreshService] runScheduledRefreshForUser failed', e);
    result.errors++;
  }

  return result;
}