/**
 * Referral base URL configuration.
 *
 * Set VITE_REFERRAL_BASE_URL in your environment (.env or hosting config) to
 * override the production host used in all referral links generated by the UI.
 *
 * The backend functions (sendReferralInvite, getOrCreateReferralProgram) use
 * the APP_URL Deno environment variable, which must match this value.
 *
 * Example .env entry:
 *   VITE_REFERRAL_BASE_URL=https://collectionkeeper.base44.app
 */
export const REFERRAL_BASE_URL = (
  import.meta.env.VITE_REFERRAL_BASE_URL || 'https://collectionkeeper.base44.app'
).replace(/\/$/, '');

/**
 * Build a referral link for the given code and optional module key.
 *
 * @param {string} referralCode
 * @param {string|null} [module] - optional module key (e.g. 'pipekeeper')
 * @returns {string}
 */
export function buildReferralLink(referralCode, module = null) {
  const base = `${REFERRAL_BASE_URL}?ref=${referralCode}`;
  return module ? `${base}&m=${module}` : base;
}
